### ISSUE TITLE
Geopandas error and importing shapefile error

### ISSUE THREAD

**Issue by Mithlesh171091** [manushibt/Py4GeoDS#5]
![Geopandas Error](https://user-images.githubusercontent.com/102284211/172595525-a3445912-723d-44ff-a17f-45cb7442f61b.JPG)
![Importing shapefile error](https://user-images.githubusercontent.com/102284211/172595536-a9cd1ac3-8c69-475a-a6dd-3557976d671a.JPG)

**Comment by manushibt** [comment]
By reading at your comment, you need to install fiona package which uses in the background to handle vector files.
